package net.juancarlosfernandez.helloworld.mybatis.mapper;

import java.util.List;
import net.juancarlosfernandez.helloworld.mybatis.domain.Myfile;
import net.juancarlosfernandez.helloworld.mybatis.domain.MyfileExample;
import org.apache.ibatis.annotations.Param;

public interface MyfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfile
     *
     * @mbggenerated Fri Dec 24 09:33:15 CET 2010
     */
    int countByExample(MyfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfile
     *
     * @mbggenerated Fri Dec 24 09:33:15 CET 2010
     */
    int deleteByExample(MyfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfile
     *
     * @mbggenerated Fri Dec 24 09:33:15 CET 2010
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfile
     *
     * @mbggenerated Fri Dec 24 09:33:15 CET 2010
     */
    int insert(Myfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfile
     *
     * @mbggenerated Fri Dec 24 09:33:15 CET 2010
     */
    int insertSelective(Myfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfile
     *
     * @mbggenerated Fri Dec 24 09:33:15 CET 2010
     */
    List<Myfile> selectByExample(MyfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfile
     *
     * @mbggenerated Fri Dec 24 09:33:15 CET 2010
     */
    Myfile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfile
     *
     * @mbggenerated Fri Dec 24 09:33:15 CET 2010
     */
    int updateByExampleSelective(@Param("record") Myfile record, @Param("example") MyfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfile
     *
     * @mbggenerated Fri Dec 24 09:33:15 CET 2010
     */
    int updateByExample(@Param("record") Myfile record, @Param("example") MyfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfile
     *
     * @mbggenerated Fri Dec 24 09:33:15 CET 2010
     */
    int updateByPrimaryKeySelective(Myfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfile
     *
     * @mbggenerated Fri Dec 24 09:33:15 CET 2010
     */
    int updateByPrimaryKey(Myfile record);
}